DROP TABLE osoba CASCADE CONSTRAINTS;
DROP TABLE pracownik CASCADE CONSTRAINTS;
DROP TABLE klient CASCADE CONSTRAINTS;
DROP TABLE auta CASCADE CONSTRAINTS;
DROP TABLE uslugi CASCADE CONSTRAINTS;
DROP TABLE naprawy CASCADE CONSTRAINTS;
DROP TABLE cennik CASCADE CONSTRAINTS;
DROP TABLE koszty_eksploatacji CASCADE CONSTRAINTS;
DROP TABLE wypozyczenia CASCADE CONSTRAINTS;
DROP TABLE zwroty CASCADE CONSTRAINTS;




